### ISSUE TITLE
テスト用サービスとして何を作るかを考える。

### ISSUE THREAD

**Issue by kohosoda** [kohosoda/test_project#1]
まずは、ツールの使い方に慣れるために、何でもいいからごく簡単なサービスを協力して作ってみる。

最初のサービスとして何を作りたいかを考える。

例）郵便番号管理サービス、じゃんけんゲーム、簡単な ECサイト

**Comment by Y-Take-Ton** [comment]
テスト　クローズ

**Comment by Y-Take-Ton** [comment]
・子供向けの教育支援サービス

**Comment by Y-Take-Ton** [comment]
・オンラインじゃんけんサービス　で決定
